### ISSUE TITLE
login?

### ISSUE THREAD

**Issue by ogrotten** [azat-co/blog-express#6]
Hey there.

I'm learning nodejs, etc. I found your project and was wanting to use it as a learning resource, something to kinda take apart.

I got it all installed and running no prob, but need to log in. I see db/users.json, but the login/pass combo (hi@azat.co / 1) doesn't do it.

how would I go about getting logged in?

Thanks for any help.

**Comment by suraj-bk** [comment]
This is happening because of incorrect code. Follow these steps to get the code working.
STEP 1:
Go to /db folder. In seed.sh file, replace the content with this
```
mongoimport --db blog --collection users --file ./users.json --jsonArray
mongoimport --db blog --collection articles --file ./articles.json --jsonArray
```

STEP 2:
run the command
```
sh seed.sh
```

STEP 3:
run express and mongod.. 

Hope everything will work then :)

**Comment by azat-co** [comment]
@suraj-bk thank you. PR merged

**Comment by aligos** [comment]
thank's Mr. Azat
